name: kencana_live_timer
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  desktop_drop: ^0.4.4
  desktop_window: ^0.4.0
  flutter:
    sdk: flutter
  flutter_file_view: ^2.2.1
  flutter_img: ^0.1.5+111
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: 5.9.0
  flutter_svg: 2.0.8
  get: 4.6.5
  iconly: 1.0.1
  intl: ^0.17.0
  pdfx: ^2.5.0
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Inter/Inter-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Inter/Inter-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Inter/Inter-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          style: italic
          weight: 800
